endpoints:
  health:
    enabled: true

#spring:
#  application:
#    name: service-1
#
#server:
#  port: 8771
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    lease-renewal-interval-in-seconds: 30
#    instance-id: service-1-8771

spring:
  application:
    name: service-1

server:
  port: 8771

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 30
    instance-id:  service-1-8771