spring:
  application:
    name: provider-user
  zipkin:
    base-url: http://localhost:8700
    enabled: true
  sleuth:
    sampler:
      percentage: 1.0

server:
  port: 8781
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 30
    instance-id:  provider-user-1-8781
logging:
  level: debug