spring:
  application:
    name: server-2

server:
  port: 8762

eureka:
  instance:
    hostname: localhost-peer2
    instance-id: eurka-server-8762
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 30000
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/