server:
  port: 8772

spring:
  application:
    name: feign-service-2

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 30
    instance-id:  feign-service-2-8772