server:
  port: 8000

spring:
  cloud:
    config:
      server:
        #git:
          #uri: https://github.com/byebyeway/spring-cloud-config/
        native:
          search-locations: file:////D:/workspace/SpringCloud/configServer
        default-profile: native
  profiles:
    active: native
  application:
    name: spring-config-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 30
    instance-id:  spring-config-server-8000
