spring:
  application:
    name: ribbon

server:
  port: 8775

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 30
    instance-id:  customer-robbin-1-8775